name: Daily Reminder

on:
  schedule:
    - cron: "50 04 * * *"
  workflow_dispatch:

jobs:
  notification:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Commit and push changes
        run: |
          echo "Hehehe 😅" >> README.md
          git config --global user.email "hoangtien2k3qx1@gmail.com"
          git config --global user.name "Hoàng Anh Tiến"
          git add -A
          git commit -m "commit daily"
          git push
